-- Migration: Create ai_solutions cache table for AI-generated solution suggestions
-- Run this against the VoiceUp Supabase/Postgres instance

BEGIN;

CREATE TABLE IF NOT EXISTS public.ai_solutions (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    problem_id uuid NOT NULL REFERENCES public.problems(id) ON DELETE CASCADE,
    suggestions jsonb NOT NULL DEFAULT '[]'::jsonb,
    model text NOT NULL,
    created_by text,
    created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS ai_solutions_problem_id_created_at_idx
    ON public.ai_solutions (problem_id, created_at DESC);

COMMENT ON TABLE public.ai_solutions IS 'Cache of Gemini generated solution suggestions per civic problem.';
COMMENT ON COLUMN public.ai_solutions.suggestions IS 'JSON array of actionable solution suggestions generated by the AI.';

COMMIT;
